security:
    enable_authenticator_manager: true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_WRITTER, ROLE_SPELLCHECKER, ROLE_JOURNALIST]

    password_hashers:
        Symfony\Component\Security\Core\User\InMemoryUser: plaintext

    providers:
        in_memory:
            memory:
                users:
                    alice: { password: password, roles: ROLE_WRITTER }
                    spellchecker: { password: password , roles: ROLE_SPELLCHECKER }
                    journalist: { password: password , roles: ROLE_JOURNALIST }
                    admin: { password: password , roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/

            logout:
                target: /
            # logout:
            #     handlers:
            #         - App\Security\YoloAuthenticator
            custom_authenticators:
                - App\Security\YoloAuthenticator
