name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: workflow_test
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d workflow_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      APP_ENV: test
      DATABASE_URL: pgsql://postgres:password@127.0.0.1:5432/workflow_test?serverVersion=16&charset=utf8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
          tools: composer:v2
          extensions: ctype, iconv, pdo_pgsql

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Setup database
        run: |
          bin/console doctrine:database:create --if-not-exists --env=test
          bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run tests
        run: bin/phpunit
